---
- name: Remove httpd and clean up
  hosts: all
  become: yes

  tasks:
    - name: Remove httpd
      yum:
        name: httpd
        state: absent

    - name: Remove html file
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Revert firewall http and https ports
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: disabled
        immediate: yes
      loop:
        - http
        - https


