---
- name: Install httpd
  hosts: all
  become: yes

  tasks:
    - name: Installing httpd
      yum:
        name: httpd
        state: present

    - name: Check httpd started
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Start firewall
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Copy html file
      copy:
        content: "<html><body><h1>Welcome to my web server</h1></body></html>\n"
        dest: /var/www/html/index.html

    - name: Open firewall http and https ports
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - http
        - https


