---
- name: User add and password change routine
  hosts: all
  become: yes
  vars_files: 
    - vars/users.yaml
    - vars/passwords.yaml

  tasks: 
    - name: Users add
      user: 
        name: "{{ item.key }}"
        comment: "{{ item.value.comment }}"
        home: "{{ item.value.homedir }}"
        state: present

      with_dict: "{{ users }}"
      notify: update_pw

  handlers:
    - name: update_pw
      user:
        name: "{{ item.key }}" 
        password: "{{ item.value.password | password_hash('sha512') }}"

      with_dict: "{{ passwords }}"
      no_log: true
