- name: configure
  template:
    src: vsftpd.j2
    dest: /etc/vsftpd/vsftpd.conf
  notify: vsftpd_restart

- name: create upload dir
  file:
    path: /var/ftp/pub/upload
    state: directory
    mode: '0775'
    owner: ftp
    group: root

